services:
  api-clients:
    build: .
    container_name: api-clients
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/api-clients
      - RABBITMQ_URI=amqp://rabbitmq
      - PORT=5001
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data:
